name: accionables

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      search_term:
        description: 'Término de búsqueda'
        required: true
        default: 'libros'

jobs:
  scraper:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 requests openpyxl

      - name: 4. Ejecutar scraper
        working-directory: ./src/edu_pad
        env:
          SEARCH_TERM: ${{ github.event.inputs.search_term || 'libros' }}
        run: |
          python scraping.py

      - name: 5. Commit y push de resultados
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Resultados scraper: ${{ github.event.inputs.search_term || 'libros' }}"
          commit_user_name: "Saimon7741 [GitHub Actions]"
          commit_user_email: simon.lara@est.iudigital.edu.co