name: accionables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scraper:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: 4. Ejecutar scraper
        run: |
          python main.py --search "percy"

      - name: 5. Commit y push de resultados
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Resultados búsqueda percy"
          commit_user_name: "Saimon7741 [GitHub Actions]"
          commit_user_email: simon.lara@est.iudigital.edu.co