name: accionables

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scraper:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Crear entorno virtual
        run: python -m venv venv

      - name: 4. Activar entorno y actualizar pip
        run: |
          .\venv\Scripts\activate
          python -m pip install --upgrade pip

      - name: 5. Instalar dependencias
        run: |
          pip install -e .

      - name: 6. Ejecutar aplicación Streamlit
        working-directory: ./src/edu_pad
        run: |
          streamlit run scraping.py

      - name: 7. Commit y push de resultados
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Genera csv"
          commit_user_name: "Saimon7741 [GitHub Actions]"
          commit_user_email: simon.lara@est.iudigital.edu.co