name: docker

on:
  push:
    branches: [main]

jobs:
  scraper:
    runs on: ubuntu-latest
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4
      - name: 2. Login Docker Github
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
